### ISSUE TITLE
user interface and data saving todo's

### ISSUE THREAD

**Issue by judithfan** [cogtoolslab/gallerize#1]
### user interface
- [x] "On/Off" toggle ==> "valid/invalid" 
- [x] Another field to filter on value of valid
- [x] Lazy Load

### data saving
- [x] insert CSV rows as records into mongo: dbname = 'gallerize' & colname = 'kiddraw_cdm'
- [x] write method to fetch images from mongodb that match values of fields in header form
- [x] write method to directly update "valid" field in mongodb upon click

**Comment by yiy142** [comment]
Socket.io
(Node) MongoDB
Node.js 
Express.js
